// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// comp_PZ_cpp
Eigen::MatrixXd comp_PZ_cpp(const Eigen::MatrixXd& Y, const List& A, const IntegerVector& m, const List& Beta, const Eigen::VectorXd& p);
RcppExport SEXP _rjcdm_comp_PZ_cpp(SEXP YSEXP, SEXP ASEXP, SEXP mSEXP, SEXP BetaSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const List& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const List& >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(comp_PZ_cpp(Y, A, m, Beta, p));
    return rcpp_result_gen;
END_RCPP
}
// sample_Z_cpp
Eigen::MatrixXd sample_Z_cpp(const Eigen::MatrixXd& Y, const List& A, const IntegerVector& m, const List& Beta, const Eigen::VectorXd& p);
RcppExport SEXP _rjcdm_sample_Z_cpp(SEXP YSEXP, SEXP ASEXP, SEXP mSEXP, SEXP BetaSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const List& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const List& >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Z_cpp(Y, A, m, Beta, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rjcdm_comp_PZ_cpp", (DL_FUNC) &_rjcdm_comp_PZ_cpp, 5},
    {"_rjcdm_sample_Z_cpp", (DL_FUNC) &_rjcdm_sample_Z_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rjcdm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
