# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

comp_PZ_cpp <- function(Y, A, m, Beta, p) {
    .Call(`_rjcdm_comp_PZ_cpp`, Y, A, m, Beta, p)
}

sample_Z_cpp <- function(Y, A, m, Beta, p) {
    .Call(`_rjcdm_sample_Z_cpp`, Y, A, m, Beta, p)
}

